### ISSUE TITLE
Video poker missing file

### ISSUE THREAD

**Issue by Mekire** [iminurnamez/pyroller#131]
@andarms 
You seem to have forgotten to include `video_poker_data` with your last commit making the program unrunnable.  I have, for the moment commented out your star imports.  This means the program starts, but will crash if anyone tries to play poker.  Please update your repo to the current one; then uncomment the star imports in dealer and machine; and add the missing file.

-Mek

**Comment by andarms** [comment]
sorry about that 😁, i fixed in the new pull request https://github.com/iminurnamez/pyroller/pull/132
