### ISSUE TITLE
Pachinko and python 3 64bit

### ISSUE THREAD

**Issue by bitcraft** [iminurnamez/pyroller#171]
Somehow, pachinko will not work on one of my test setups:
- windows 8.1
- python 3.4 64 bit

Opening pachinko will crash with a message about an unsolvable constraint.  With some debugging, i've noticed that a lot of the math is off.  I'll make it a point to go through it.  I'd like to keep pymunk around for other casino games...like roulette, maybe.

On 32 bit python 2.7 it runs fine.  Perhaps this is a pymunk issue, i am not sure right now.

**Comment by Mekire** [comment]
My Linux Mint 17 doesn't crash on py3 64 but I do get errors.
This error is reported to the terminal repeatedly if I try adding balls to pachinko.  I can still stop it and return to the lobby with no program crash however.  Map returns generator in py3 so this was causing an issue.  Not sure if it fixes your problem though.
```python
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 277, in 'calling callback function'
  File "/home/sean/Documents/repos/pyroller/pymunk/__init__.py", line 527, in cf
    x = func(self, arbiter, *args, **kwargs)
  File "/home/sean/Documents/repos/pyroller/data/states/pachinko/playfield.py", line 401, in new_ball
    self.add(Ball(space, self._plunger.ball_chute))
  File "/home/sean/Documents/repos/pyroller/data/states/pachinko/playfield.py", line 250, in __init__
    image = smoothscale(prepare.GFX.get('ball-bearing'), size)
TypeError: must be 2-item sequence, not map
```

**Comment by iminurnamez** [comment]
Runs fine on 32-bit py3.4, too (Windows 8.1)

**Comment by Mekire** [comment]
Can this issue be closed or is it still on-going?

**Comment by bitcraft** [comment]
all i can say is...stats.  let's keep it open until tomorrow.

On Fri, Jul 10, 2015 at 1:16 AM, Sean J. McKiernan <notifications@github.com
