### ISSUE TITLE
Blackjack: returning to lobby after betting.

### ISSUE THREAD

**Issue by Mekire** [iminurnamez/pyroller#41]
If the player returns to the lobby at any time after betting they silently lose their money.  I think this is actually necessary to avoid cheating by returning to the lobby whenever a hand is unfavorable, however you might want a warning prompt.  

"Returning to the lobby will forfeit your bet.  Are you sure?"

Just a thought,
-Mek

**Comment by iminurnamez** [comment]
It's intentional for that very reason, but, a warning is a good idea. Will do.
