### ISSUE TITLE
Chips.  running out of small change.

### ISSUE THREAD

**Issue by Mekire** [iminurnamez/pyroller#92]
It is possible for the player to have a lot of money in black chips but no smaller chips; making small bets impossible.  We need some sort of function that assures a player always has small denominations when possible.

Example:
Player has $300.
Instead of just 3 black chips, he should have:
2 black, 3 blue, 1 green, 2 red, 5 white.
Or similar.

Alternately you could implement a method for the player to voluntarily break his chips into smaller denominations.

Not a critical need, but annoying when playing blackjack and you only have blacks left.
-Mek

**Comment by bitcraft** [comment]
I like the suggestion where chips could be broken up automatically.  Maybe a quick popup or non modal notification that mentions that the next highest denomination will be broken so that you small be can be made.

**Comment by iminurnamez** [comment]
You can make change by dragging chip/s to the dealer's chip rack. I recently changed how making change worked for the opposite reason. Previously, I made change by subtracting one from the total, making change for that amount and then adding a $1 chip. This meant changing a $100 chip eventually resulted in a ton of $1 chips. As it is now, dropping a chip onto the chip rack breaks it into the smallest number of lower denomination chips possible (e.g. a $25 chip becomes two $10s and a $5).

**Comment by Mekire** [comment]
Oh, well I guess this can be closed then.  I had no clue that was a feature (though I did wonder what the purpose of the rack was).  This would be a good thing for the tentative advisor popup I guess. xD.

**Comment by iminurnamez** [comment]
I think I'll add some text to the "table" at least.
